import assert from "node:assert/strict";
import { afterEach, describe, it } from "node:test";
import type { Update } from "grammy/types";
import { createBotHarness, type BotHarness } from "./helpers/botHarness.js";

const CHAT_ID = -100777;
const CYRILLIC = "\u043f\u0440\u0438\u0432\u0435\u0442 \u043a\u0430\u043a \u0442\u0432\u043e\u0438 \u0434\u0435\u043b\u0430 \u0441\u0435\u0433\u043e\u0434\u043d\u044f";
const harnesses: BotHarness[] = [];
function makeHarness(): BotHarness { const value = createBotHarness(); harnesses.push(value); return value; }
afterEach(() => { for (const value of harnesses) value.cleanup(); harnesses.length = 0; });
function enable(value: BotHarness): void { value.db.setSetting("language_moderation:enabled", "true"); value.db.setSetting("language_moderation:target", String(CHAT_ID)); }
function message(id: number, text: string, userId = 1, chatId = CHAT_ID): Update { return { update_id: id, message: { message_id: id, date: 1, from: { id: userId, is_bot: false, first_name: "User", username: `user${userId}` }, chat: { id: chatId, type: "supergroup", title: "Public" }, text } }; }
async function runPendingWarning(value: BotHarness): Promise<void> { const { processPendingWarning } = await import("../src/bot.js"); await processPendingWarning(value.bot.api, value.db, CHAT_ID); }
async function processDue(value: BotHarness): Promise<void> { const state = value.db.getLanguageModerationChatState(CHAT_ID)!; value.db.upsertLanguageModerationChatState(CHAT_ID, { lastWarningMessageId: state.last_warning_message_id, lastWarningAt: state.last_warning_at, ordinaryMessagesSinceWarning: state.ordinary_messages_since_warning, pendingWarningDueAt: new Date(0).toISOString(), pendingWarningStartedAt: state.pending_warning_started_at }); await runPendingWarning(value); }
function reactionEmoji(value: BotHarness): string | undefined {
  const reaction = value.findApiCalls("setMessageReaction")[0]?.payload.reaction;
  if (!Array.isArray(reaction)) return undefined;
  const firstReaction = reaction[0];
  return typeof firstReaction === "object" && firstReaction !== null && "emoji" in firstReaction && typeof firstReaction.emoji === "string" ? firstReaction.emoji : undefined;
}

describe("public language moderation", () => {
  it("does nothing while disabled", async () => { const value = makeHarness(); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(value.countApiCalls("sendMessage"), 0); });
  it("persists one pending aggregation window for distinct zero-strike users", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC, 1)); await value.bot.handleUpdate(message(2, CYRILLIC, 2)); const state = value.db.getLanguageModerationChatState(CHAT_ID)!; assert.ok(state.pending_warning_started_at); assert.ok(state.pending_warning_due_at); assert.equal(value.countApiCalls("sendMessage"), 0); });
  it("groups users once after the pending window becomes due", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC, 1)); await value.bot.handleUpdate(message(2, CYRILLIC, 1)); await value.bot.handleUpdate(message(3, CYRILLIC, 2)); await processDue(value); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 1); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 2)?.current_strikes, 1); assert.equal(value.countApiCalls("setMessageReaction"), 2); assert.equal(value.findApiCalls("sendMessage").filter((call) => call.payload.chat_id === CHAT_ID).length, 1); });
  it("ignores another public chat", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC, 1, -100778)); assert.equal(value.db.getLanguageModerationUserState(-100778, 1), undefined); });
  it("does not write private support bans", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(value.db.getBannedUser(1), undefined); });
  it("keeps ordinary English messages harmless", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, "hello there normal message")); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1), undefined); });
  it("keeps private messages outside moderation", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate({ update_id: 1, message: { message_id: 1, date: 1, from: { id: 1, is_bot: false, first_name: "User" }, chat: { id: 1, type: "private", first_name: "User" }, text: CYRILLIC } }); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1), undefined); });
  it("preserves one first strike across repeat violations", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC)); await value.bot.handleUpdate(message(2, CYRILLIC)); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1), undefined); await processDue(value); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 1); });
  it("counts target ordinary messages", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, "hello normal message")); assert.equal(value.db.getLanguageModerationChatState(CHAT_ID)?.ordinary_messages_since_warning, 1); });
  it("stores warning state after pending processing", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC)); const before = value.db.getLanguageModerationChatState(CHAT_ID)!; assert.equal(before.last_warning_at, null); await processDue(value); const after = value.db.getLanguageModerationChatState(CHAT_ID)!; assert.ok(after.last_warning_at); assert.equal(after.pending_warning_due_at, null); assert.equal(after.ordinary_messages_since_warning, 0); });
  it("keeps staff chat isolated", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC, 1, -100900)); assert.equal(value.db.getLanguageModerationUserState(-100900, 1), undefined); });
  it("does not advance on duplicate message ids", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC)); await value.bot.handleUpdate(message(1, CYRILLIC)); await processDue(value); await runPendingWarning(value); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 1); assert.equal(value.countApiCalls("sendMessage"), 1); });
  it("keeps allowlisted names non-actionable", async () => { const value = makeHarness(); enable(value); value.db.setSetting("language_moderation:allowlist", JSON.stringify([CYRILLIC])); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1), undefined); });
  it("persists moderation target settings", () => { const value = makeHarness(); value.db.setSetting("language_moderation:target", String(CHAT_ID)); assert.equal(value.db.getSetting("language_moderation:target"), String(CHAT_ID)); });
  it("keeps an elapsed cooldown suppressed without ordinary-message threshold", async () => { const value = makeHarness(); enable(value); value.db.upsertLanguageModerationChatState(CHAT_ID, { lastWarningMessageId: 9, lastWarningAt: new Date("2000-01-01T00:00:00.000Z").toISOString(), ordinaryMessagesSinceWarning: 1 }); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 1); assert.equal(value.db.getLanguageModerationChatState(CHAT_ID)?.pending_warning_due_at, null); });
  it("uses eyes for an immediate first strike", async () => { const value = makeHarness(); enable(value); value.db.upsertLanguageModerationChatState(CHAT_ID, { lastWarningMessageId: 9, lastWarningAt: new Date().toISOString(), ordinaryMessagesSinceWarning: 0 }); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(reactionEmoji(value), "\u{1F440}"); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 1); });
  it("uses eyes for a second strike", async () => { const value = makeHarness(); enable(value); value.db.upsertLanguageModerationUserState({ chat_id: CHAT_ID, user_telegram_id: 1, username: "user1", current_strikes: 1, sanction_tier: 0, first_strike_at: new Date().toISOString() }); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(reactionEmoji(value), "\u{1F440}"); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 2); });
  it("uses eyes for delayed grouped warnings", async () => { const value = makeHarness(); enable(value); await value.bot.handleUpdate(message(1, CYRILLIC)); await processDue(value); assert.equal(reactionEmoji(value), "\u{1F440}"); });
  it("persists a strike when its reaction fails", async () => { const value = makeHarness(); enable(value); value.db.upsertLanguageModerationChatState(CHAT_ID, { lastWarningMessageId: 9, lastWarningAt: new Date().toISOString(), ordinaryMessagesSinceWarning: 0 }); value.failNextApiCall("setMessageReaction"); await value.bot.handleUpdate(message(1, CYRILLIC)); assert.equal(value.db.getLanguageModerationUserState(CHAT_ID, 1)?.current_strikes, 1); assert.equal(value.db.getSetting("language_moderation:enabled"), "true"); });
});
